### ISSUE TITLE
Improve existing cloning instructions

### ISSUE THREAD

**Issue by knightcube** [NITDgpOS/Medium_Grabber#10]
Please suggest some links to setup selenium and Firefox Webdriver. I installed selenium using `pip install selenium` but how do I setup Firefox Webdriver?

**Comment by ZER-0-NE** [comment]
Hey @knightcube 
This may help: https://selenium-python.readthedocs.io/installation.html
If this works out, feel free to elaborate the steps in the readme :)
Lemme know how it goes.
