### ISSUE TITLE
Making the script work with chrome.

### ISSUE THREAD

**Issue by AniruddhaChattopadhyay** [NITDgpOS/Medium_Grabber#14]
We could try to assess what browsers the system has installed and accordingly run the script for chrome or Firefox. In case if both Firefox and chrome are installed then the default browser will be choose. If neither of them are the default browser then Firefox will be used.

**Comment by ZER-0-NE** [comment]
Hey @AniruddhaChattopadhyay 
You can send a PR for this. Seems like a good catch!

**Comment by AniruddhaChattopadhyay** [comment]
Thanks. Working on it now.
