### ISSUE TITLE
Generate a pdf file instead of text file

### ISSUE THREAD

**Issue by ZER-0-NE** [NITDgpOS/Medium_Grabber#3]
A pdf file with all the added hyperlinks instead of the text file.

**Comment by dheeraj135** [comment]
This is the simplest way to achieve this task: https://github.com/JazzCore/python-pdfkit .

**Comment by ZER-0-NE** [comment]
Hey @dheeraj135 
You can send a PR instead.

**Comment by dheeraj135** [comment]
I am working on this issue.

**Comment by ZER-0-NE** [comment]
Sure @dheeraj135
