### ISSUE TITLE
Encrypt password

### ISSUE THREAD

**Issue by AdirthaBorgohain** [NITDgpOS/Medium_Grabber#30]
At the current stage, the login is very unsecure. Anyone and everyone can open the password.txt file and see what is the password. I think encrypting the password.txt would provide a sense of security to the user?
I can work on this if you like.

**Comment by ZER-0-NE** [comment]
Good catch.
How do you plan on implementing it?

**Comment by AdirthaBorgohain** [comment]
There's this python module called pycrypto which can make AES,DES encryption of files possible. What I plan to do is take the password as an user input for the first time and encrypt the password in a file. Then for subsequent runs, the password can be decrypted as and when needed through the module.

**Comment by ZER-0-NE** [comment]
You are free to make another script for it. I would not like all the functionalities in the same script.

**Comment by AdirthaBorgohain** [comment]
Sure. I will be creating a separate script.
