### ISSUE TITLE
Run Medium_Grabber from main file as well as the web app.

### ISSUE THREAD

**Issue by ZER-0-NE** [NITDgpOS/Medium_Grabber#36]
There is an error when we try to run Medium_Grabber from the main script.
Open for fruitful contributors.

**Comment by ZER-0-NE** [comment]
yep

**Comment by pratikmishra356** [comment]
Then I  had added another separate  file in the repository and we can run the script separately.

**Comment by ZER-0-NE** [comment]
Where exactly?
I didn't get time to run it on my machine.

**Comment by pratikmishra356** [comment]
I raised PR to add Grab_that_article_on_Medium1.py file.
