### ISSUE TITLE
A GUI for Medium_Grabber

### ISSUE THREAD

**Issue by ZER-0-NE** [NITDgpOS/Medium_Grabber#4]

**Comment by Deathrow77** [comment]
Hi. I am interested to work on this issue.

**Comment by ZER-0-NE** [comment]
Sure! Go ahead.
Do you have some layout for this issue?
I was thinking of a simple layout with some user options. We can add on more as we proceed. And what framework are you willing to use?

**Comment by Deathrow77** [comment]
I have worked on PyQt and tkinter. I can work with either of them, as per your requirement. If you have any layout in mind already, that would be helpful. Otherwise, I will make one.

**Comment by ZER-0-NE** [comment]
As of now, I don't have any particular layout. Maybe I'll keep this on hold until then.
You are free to develop one by yourself on a new branch
