### ISSUE TITLE
Running Geckodriver in headless mode

### ISSUE THREAD

**Issue by dheeraj135** [NITDgpOS/Medium_Grabber#7]
Geckodriver can be used in headless mode to improve user experience.

**Comment by Deathrow77** [comment]
Hi. Please Check my pull request (PR #12) solving this issue.

**Comment by dheeraj135** [comment]
> Hi. Please Check my pull request (PR #12) solving this issue.
@Deathrow77 You can add `Closes #N` in your PR message and information of PR will be reflected on the issue page, i.e. here.

**Comment by ZER-0-NE** [comment]
Solved by #12
